# Note: This is internal Klarna stuff for our test enviroment. This file is
# necessary for Klarna's build process, but remove it in the open source
# version of KATT.

ERLC_FLAGS+= -I ../../../test/test/include -pz ../../../test/shared/ebin
include ../../../support/stderl.mk
