#!/usr/bin/env escript

%% Compiles a parser module for the API blueprint format from the Neotoma
%% grammar file.

main(_) ->
  Neotoma = filename:dirname(escript:script_name()) ++ "/../deps/neotoma/ebin",
  code:add_pathz(filename:absname(Neotoma)),
  neotoma:file("priv/katt_blueprint.peg", [{output, "src/"}]).
