#!/usr/bin/env escript

%% Compiles a parser module for the API blueprint format from the Neotoma
%% grammar file.

main(_) ->
    %% Katt is the main project
    Neotoma1 = filename:dirname(escript:script_name()) ++ "/../_build/default/lib/neotoma/ebin",
    %% Katt is a dependency
    Neotoma2 = filename:dirname(escript:script_name()) ++ "/../../neotoma/ebin",
    code:add_pathz(filename:absname(Neotoma1)),
    code:add_pathz(filename:absname(Neotoma2)),
    neotoma:file("priv/katt_blueprint.peg", [{output, "src/"}]).
