%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% @doc KATT Blueprint
%%%
%%% This is a placeholder module for the code that is being generated by
%%% Neotoma in priv/compile-parser. The reason is that some tools need the
%%% .erl file to exist when doing xref checks or else they will fail.
%%% Besides that this file serves no purpose.
%%%
%%% @copyright 2013 Klarna AB
%%% @end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

-module(katt_blueprint).

-export([ file/1
        , parse/1
        ]).

-include("blueprint_types.hrl").

%%% These definitions are just placeholders for some xref checks. The beam file
%%% to use is generated by the script priv/compile-parser.

-spec file(string()) -> #katt_blueprint{}.
%% @doc Parse a KATT Blueprint file.
file(_) -> #katt_blueprint{ name = "Placeholder" }.

%% @doc Parse a KATT Blueprint string.
-spec parse(string()) -> #katt_blueprint{}.
parse(_) -> #katt_blueprint{ name = "Placeholder" }.
